version: "3"

services:

  web:
    container_name: my_serv_qr
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: >
              sh -c "python3 p.py"